### ISSUE TITLE
Seems to crash on dependency imports for me

### ISSUE THREAD

**Issue by nathan-mill** [zagaran/eb-ssm#5]
I'd absolutely love to use this, but this is all I get after installing and going through the setup. Is it not able to run in a venv or something?

```
Traceback (most recent call last):
  File "/Users/nate/dev/myproject/.venv/bin/eb-ssm", line 5, in <module>
    from eb_ssm.eb_ssm import main
  File "/Users/nate/dev/myproject/.venv/lib/python3.11/site-packages/eb_ssm/eb_ssm.py", line 8, in <module>
    from ebcli.lib.elasticbeanstalk import get_all_environment_names
ImportError: cannot import name 'get_all_environment_names' from 'ebcli.lib.elasticbeanstalk' (/Users/nate/dev/myproject/.venv/lib/python3.11/site-packages/ebcli/lib/elasticbeanstalk.py)
```

**Comment by alvinsiu** [comment]
Thanks for reporting this, @nathan-mill. It looks like the import doesn't exist if you're using `awsebcli<3.14.0`. If you upgrade to `awsebcli>=3.14.0` it should work.

We'll include the dependency specification in the next release.

**Comment by nathan-mill** [comment]
Fabulous. Thanks for digging.
